/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    return [
      { source: '/articles/common-renovation-mistakes', destination: '/articles/basement-renovation-mistakes', statusCode: 301 },
      { source: '/articles/basement-waterproofing-costs', destination: '/articles/basement-waterproofing-cost', statusCode: 301 },
      { source: '/articles/mold-prevention', destination: '/articles/how-to-prevent-basement-mold', statusCode: 301 },
      { source: '/articles/sump-pump-guide', destination: '/articles/sump-pump-buying-guide', statusCode: 301 },
      { source: '/articles/efflorescence-explainer', destination: '/articles/basement-efflorescence', statusCode: 301 },
      { source: '/articles/finishing-a-basement', destination: '/articles/basement-finishing-cost', statusCode: 301 },
      { source: '/articles/basement-mold-prevention', destination: '/articles/how-to-prevent-basement-mold', statusCode: 301 },
      { source: '/articles/sump-pump-installation-guide', destination: '/articles/sump-pump-cost', statusCode: 301 },
      { source: '/articles/how-to-hire-a-basement-contractor', destination: '/articles/how-to-hire-basement-waterproofing-contractor', statusCode: 301 },
      { source: '/articles/sump-pump-installation-cost', destination: '/articles/sump-pump-cost', statusCode: 301 },
      { source: '/articles/why-basement-floods-without-rain', destination: '/articles/why-basement-floods-with-sump-pump', statusCode: 301 },
      { source: '/articles/basement-humidity', destination: '/articles/basement-humidity-guide', statusCode: 301 },
      { source: '/articles/basement-waterproofing-methods', destination: '/articles/complete-basement-waterproofing-guide', statusCode: 301 },
      { source: '/articles/basement-waterproofing-guide', destination: '/articles/complete-basement-waterproofing-guide', statusCode: 301 },
      { source: '/articles/basement-waterproofing-cost-guide', destination: '/articles/basement-waterproofing-cost', statusCode: 301 },
      { source: '/articles/basement-insulation', destination: '/articles/basement-insulation-guide', statusCode: 301 },
      { source: '/articles/how-to-hire-a-waterproofing-contractor', destination: '/articles/how-to-hire-basement-waterproofing-contractor', statusCode: 301 },
      { source: '/articles/best-sump-pumps', destination: '/articles/best-sump-pumps-2026', statusCode: 301 },
      { source: '/articles/diy-vs-pro-basement-waterproofing', destination: '/articles/diy-vs-hiring-pro-basement-projects', statusCode: 301 },
      { source: '/articles/how-to-dry-out-basement', destination: '/articles/how-to-dry-out-basement-after-flooding', statusCode: 301 },
      { source: '/articles/basement-permits', destination: '/articles/basement-permits-guide', statusCode: 301 },
      { source: '/guides/bowing-basement-walls', destination: '/articles/bowing-basement-walls', statusCode: 301 },
      { source: '/guides/best-vapor-barriers', destination: '/articles/best-vapor-barriers', statusCode: 301 },
      { source: '/articles/smart-sump-pumps', destination: '/articles/smart-sump-pumps-guide', statusCode: 301 },
      { source: '/articles/pre-finish-audit-checklist', destination: '/articles/pre-finish-audit', statusCode: 301 },
      { source: '/articles/crawl-space-vs-basement', destination: '/articles/basement-vs-crawl-space-vs-slab', statusCode: 301 },
      { source: '/articles/basement-waterproofing', destination: '/articles/complete-basement-waterproofing-guide', statusCode: 301 },
      { source: '/guides/waterproofing', destination: '/articles/complete-basement-waterproofing-guide', statusCode: 301 },
      { source: '/articles/efflorescence', destination: '/articles/basement-efflorescence', statusCode: 301 },
      { source: '/articles/waterproofing-finances', destination: '/articles/basement-waterproofing-finances-insurance-taxes', statusCode: 301 },
      { source: '/guides/how-to-hire-waterproofing-contractor', destination: '/articles/how-to-hire-basement-waterproofing-contractor', statusCode: 301 },
      { source: '/guides/interior-vs-exterior-waterproofing', destination: '/articles/interior-vs-exterior-waterproofing', statusCode: 301 },
      { source: '/articles/how-to-hire-waterproofing-contractor', destination: '/articles/how-to-hire-basement-waterproofing-contractor', statusCode: 301 },
      { source: '/articles/radon-testing-mitigation', destination: '/articles/radon-testing-and-mitigation', statusCode: 301 },
      { source: '/cost-guides/foundation-crack-repair', destination: '/articles/foundation-crack-repair-cost', statusCode: 301 },
      { source: '/articles/homebuyers-inspection-checklist', destination: '/articles/homebuyers-basement-inspection-checklist', statusCode: 301 },
      { source: '/guides/old-house-basements', destination: '/articles/old-house-basements', statusCode: 301 },
      { source: '/articles/basement-radon-testing-mitigation-guide', destination: '/articles/radon-testing-and-mitigation', statusCode: 301 },
      { source: '/articles/crawl-space-encapsulation', destination: '/articles/crawl-space-encapsulation-guide', statusCode: 301 },
      { source: '/articles/submersible-vs-pedestal-sump-pumps', destination: '/articles/submersible-vs-pedestal-sump-pump', statusCode: 301 },
      { source: '/guides/homebuyers-inspection-checklist', destination: '/articles/homebuyers-basement-inspection-checklist', statusCode: 301 },
      { source: '/articles/basement-flooding-causes', destination: '/articles/basement-emergency-water-plan', statusCode: 301 },
    ]
  },
}

module.exports = nextConfig