export interface Article {
  title: string
  description: string
  slug: string
  category: string
  readTime: string
  image?: string
}

export const articles: Article[] = [
  {
    title: 'Bowing Basement Walls: Causes, Repair Methods & Cost',
    description: 'A comprehensive guide to bowing basement walls. Causes like hydrostatic pressure, early warning signs, repair methods from carbon fiber straps to wall anchors, and updated costs averaging $4,500 nationally.',
    slug: 'bowing-basement-walls',
    category: 'Structural',
        readTime: '22 min read',
    image: '/bowed%20walled.jpg',
  },
  {
    title: 'Types of Foundation Cracks: What Each One Means',
    description: 'Not all cracks are created equal. Use this 2026 diagnostic guide to determine if your foundation crack is a minor cosmetic issue or a structural red flag.',
    slug: 'types-of-foundation-cracks',
    category: 'Diagnosis',
    readTime: '15 min read',
    image: '/cracked%20foundation.jpg',
  },
  {
    title: 'Basement vs. Crawl Space vs. Slab: Which Foundation is Right for You?',
    description: 'Choosing a foundation is the most consequential decision in home construction. We compare the three major types on cost, longevity, and lifestyle.',
    slug: 'basement-vs-crawl-space-vs-slab',
    category: 'Comparison',
    readTime: '25 min read',
    image: '/crawlspace.jpg',
  },
  {
    title: 'How to Prevent Basement Mold: The Definitive Guide',
    description: 'Mold is a biological threat. Learn the 5 pillars of permanent mold prevention for your basement.',
    slug: 'how-to-prevent-basement-mold',
    category: 'Health & Safety',
    readTime: '22 min read',
    image: '/mold3.png',
  },
  {
    title: 'The Complete Basement Waterproofing Guide for 2026',
    description: 'Everything you need to know about stopping basement leaks for good. From hydrostatic pressure to sump pumps, this comprehensive guide covers all aspects of basement waterproofing.',
    slug: 'complete-basement-waterproofing-guide',
    category: 'Waterproofing',
    readTime: '35 min read',
    image: '/exterior-waterproofing-membrane.jpg.png',
  },
  {
    title: 'Interior vs. Exterior Basement Waterproofing: The Ultimate 2026 Comparison',
    description: 'A 5,000-word deep dive into which method is best for your foundation, covering costs, longevity, and effectiveness.',
    slug: 'interior-vs-exterior-waterproofing',
    category: 'Deep Dive',
    readTime: '25 min read',
    image: '/foundation-exterior-membrane-wide.jpg.png',
  },
  {
    title: 'Basement Insulation: The 2026 Guide',
    description: 'Rigid foam vs. spray foam vs. mineral wool. How to stop energy loss and prevent condensation issues.',
    slug: 'basement-insulation-guide',
    category: 'Insulation',
    readTime: '15 min read',
    image: '/unfinished-basement-interior.jpg.jpg',
  },
  {
    title: "Basement Finishing Cost Guide 2026: What You'll Actually Pay",
    description: 'How much does it cost to finish a basement in 2026? Real pricing from $20 to $75 per sq ft, full breakdowns by size, room type, and region.',
    slug: 'basement-finishing-cost',
    category: 'Cost Guide',
    readTime: '18 min read',
    image: '/images/finishingbasementhero.jpg',
  },
  {
    title: 'Egress Window Installation Cost 2026',
    description: 'How much does it cost to install an egress window in 2026? Permits, excavation, drainage, and labor costs explained.',
    slug: 'egress-window-cost',
    category: 'Cost Guide',
    readTime: '12 18 read',
    image: '/egresswindow.jpg',
  },
  {
    title: 'The Pre-Finish Audit: 7 Critical Checkpoints',
    description: 'These 7 checkpoints will future-proof your basement before you hang a single sheet of drywall.',
    slug: 'pre-finish-audit',
    category: 'Finishing',
    readTime: '10 min read',
    image: '/unfinished-basement-interior.jpg.jpg',
  },
  {
    title: 'Best Waterproof Flooring for Basements 2026',
    description: 'The complete 2026 guide to basement flooring. Compare LVP, Porcelain Tile, Laminate, Engineered Hardwood, Rubber, Epoxy, Carpet Tiles and Polished Concrete on waterproof ratings, durability, cost, and ROI.',
    slug: 'best-basement-flooring',
    category: 'Reviews',
    readTime: '130min read',
    image: '/basement-flooring-installation.jpg.png',
  },
  {
    title: 'Smart Sump Pumps & Leak Sensors: The 2026 Guide',
    description: 'IoT flood prevention systems that text you before disasters. Matter protocol, Thread networks, and predictive monitoring explained.',
    slug: 'smart-sump-pumps-guide',
    category: 'Smart Home',
    readTime: '14 min read',
        image: '/images/smart-sump-pumps-guide/smartleaksensor.jpg',
  },
  {
    title: 'Battery vs Water-Powered Sump Pumps: 2026 Comparison',
    description: 'Power vs. physics: Which backup sump pump system is right for your home? Complete 2026 comparison with costs and flow rates.',
    slug: 'battery-vs-water-powered-sump-pumps',
    category: 'Comparison',
    readTime: '11 min read',
    image: '/sump-pump-installation.jpg',
  },
  {
    title: 'What is Crystalline Waterproofing? Self-Healing Concrete Technology',
    description: 'Discover how crystalline waterproofing creates self-healing concrete foundations. The invisible armor revolutionizing basement protection.',
    slug: 'crystalline-waterproofing',
    category: 'Technology',
    readTime: '12 min read',
    image: '/images/Crystalline-Waterproofing-Systems.jpg',
  },
  {
    title: 'Foundation Crack Repair Cost 2026',
    description: 'Epoxy injection vs. polyurethane foam. Expect to pay $350-1,500 per crack depending on severity and method.',
    slug: 'foundation-crack-repair-cost',
    category: 'Cost Guide',
    readTime: '12 min read',
    image: '/foundation-crack-closeup.jpg',
  },
  {
    title: 'French Drain Installation Cost 2026',
    description: 'Full cost breakdown for yard and interior French drains. Average $1,000-6,500 depending on length and type.',
    slug: 'french-drain-cost',
    category: 'Cost Guide',
    readTime: '10 min read',
    image: '/french-drain-trench.jpg',
  },
  {
    title: 'Sump Pump Installation Cost 2026',
    description: 'Pedestal vs. submersible pump pricing, pit excavation, and battery backup costs explained.',
    slug: 'sump-pump-cost',
    category: 'Cost Guide',
    readTime: '9 min read',
    image: '/sump-pump-pit-closeup.jpg.png',
  },
  {
    title: 'Mold Remediation Cost 2026',
    description: 'Professional mold removal costs $500-$10,000+ by area size. What drives the price and when to call a pro.',
    slug: 'mold-remediation-cost',
    category: 'Health & Safety',
    readTime: '8 min read',
    image: '/basement-mold-wall.jpg',
  },
  {
        title: "Basement Waterproofing Cost 2026: What You'll Actually Pay",
    description: 'How much does basement waterproofing cost in 2026? National average $5,230. Interior systems $3,000-$8,000, exterior $8,000-$15,000. Full cost breakdown by method.',
    slug: 'basement-waterproofing-cost',
    category: 'Cost Guide',
    readTime: '18 min read',
    image: '/foundation-waterproofing-construction.jpg.png',
  },
  {
    title: 'Sump Pump Buying Guide: How to Choose the Right One (2026)',
    description: 'From horsepower to pump types, everything you need to know to choose the right sump pump and protect your basement from flooding.',
    slug: 'sump-pump-buying-guide',
    category: 'Buying Guide',
    readTime: '12 min read',
    image: '/sump-pump-installation.jpg',
  },
  {
    title: 'Why Your Basement Floods Even With a Sump Pump (And How to Fix It)',
    description: 'Having a sump pump does not guarantee a dry basement. Here are the most common reasons how to diagnose each one, and what to do about it. From power outages to drainage failures.',
    slug: 'why-basement-floods-with-sump-pump',
    category: 'Troubleshooting',
    readTime: '18 min read',
    image: '/basement-flooding.jpg',
  },
  {
    title: 'How to Finish a Basement: The Complete 2026 Guide',
    description: 'From permits and moisture science to framing, egress, and lighting. The complete structural, legal, and aesthetic roadmap for finishing your basement in 2026.',
    slug: 'how-to-finish-a-basement',
    category: 'Finishing',
    readTime: '35 min read',
    image: '/images/finishingbasementhero.jpg',
  },
  {
    title: 'Dehumidifier Myths: Why Your 30-Pint Unit Is Failing',
    description: 'Why your 30-pint unit is failing and the science-based guidelines to choose the right dehumidifier for your space.',
    slug: 'dehumidifier-myths',
    category: 'Health & Safety',
    readTime: '30 min read',
    image: '/Dehumidifier%20Myths-hero%20image.jpg',
  },
  {
    title: 'Radon and Basement Waterproofing: How Sealing Reduces Radon Risks',
    description: 'How sealing your home reduces radon risks and prevents water damage — your complete 2026 guide.',
    slug: 'radon-and-basement-waterproofing',
    category: 'Health & Safety',
    readTime: '28 min read',
    image: '/Radon%20and%20waterproofing.jpg',
  },
  {
    title: 'How Much Value Does Waterproofing Add to Your Home Appraisal?',
    description: 'A professionally waterproofed basement protects your home and boosts its market appeal — here is what the numbers say for 2026.',
    slug: 'waterproofing-home-appraisal-value',
    category: 'Home Value',
    readTime: '22 min read',
    image: '/Home%20apprasial%20.jpg',
  },
  {
    title: "The Homebuyer's Basement Inspection Checklist",
    description: 'A detailed 2026 checklist to spot hidden mold, fresh paint cover-ups, water damage, and foundation issues before you buy.',
    slug: 'homebuyers-basement-inspection-checklist',
    category: 'Buying Guide',
    readTime: '25 min read',
    image: '/homebuyers%20checklist.jpg',
  },
  {
    title: 'How to Hire a Basement Waterproofing Contractor Without Getting Scammed',
    description: 'A step-by-step guide to vetting contractors, spotting scams, asking the right questions, and getting realistic 2026 pricing.',
    slug: 'how-to-hire-basement-waterproofing-contractor',
    category: 'Hiring Guide',
    readTime: '20 min read',
    image: '/howto%20hire%20a%20contractor%20.jpg',
  },
  {
    title: 'Water in My Basement: Your Immediate Emergency Plan',
    description: 'If water is flooding your basement right now, follow this step-by-step emergency plan. Safety first, stop the source, remove water fast.',
    slug: 'basement-emergency-water-plan',
    category: 'Emergency',
    readTime: '6 min read',
    image: '/Flooded%20Basement.jpg',
  },
  {
    title: 'Basement Renovation Mistakes: The 10 Most Expensive Errors',
    description: 'Avoid the 10 most costly basement renovation mistakes. Real 2026 fix costs from $2,000 to $25,000 and how to dodge each one.',
    slug: 'basement-renovation-mistakes',
    category: 'Renovation',
    readTime: '18 min read',
    image: '/Basement%20renovation%20mistakes.jpg',
  },
  {
    title: 'Musty Basement Smell: Causes, Fixes, and How to Eliminate It for Good',
    description: 'Find out what causes that musty basement smell and how to get rid of it permanently. Covers mold, humidity, drain issues, and proven fixes.',
    slug: 'musty-basement-smell',
    category: 'Health & Safety',
    readTime: '14 min read',
    image: '/%3AMusty%20Basement%20Smell.jpg',
  },
  {
    title: 'Basement Efflorescence: What That White Powder Really Means',
    description: 'Learn what causes white powder on basement walls, whether efflorescence is dangerous, how to clean it safely, and how to stop it from returning.',
    slug: 'basement-efflorescence',
    category: 'Diagnosis',
    readTime: '12 min read',
    image: '/Efflorescence.jpg',
  },
  {
    title: 'Basement ADU & Rental Suite: How to Create a Profitable Legal Basement Apartment',
    description: 'Complete 2026 guide to converting your basement into a legal ADU or rental suite. Waterproofing, egress, zoning, costs, and design tips.',
    slug: 'basement-adu-rental-suite',
    category: 'Finishing',
    readTime: '18 min read',
        image: '/images/basement-adu-rental-suite/ADUbasement.jpg',
  },
  {
    title: 'Basement Bathroom Guide: How to Add a Bathroom the Right Way',
    description: 'Complete 2026 guide to adding a bathroom in your basement. Costs, plumbing options, waterproofing, materials, and step-by-step planning.',
    slug: 'basement-bathroom-guide',
    category: 'Finishing',
    readTime: '20 min read',
    image: '/Basement%20Bathroom.jpg',
  },
  {
    title: 'Basement Home Gym Guide: How to Build a Great Workout Space Below Ground',
    description: 'Complete 2026 guide to building a basement home gym. Waterproofing, flooring, equipment, ventilation, and costs explained in plain English.',
    slug: 'basement-home-gym',
    category: 'Finishing',
    readTime: '18 min read',
    image: '/gym%20image.jpg',
  },
  {
    title: 'Old House Basements: Complete Guide to Renovating, Waterproofing & Insulating Older Homes',
    description: 'Everything you need to know about renovating, waterproofing, and insulating basements in homes built before 1950. Work with the original materials, not against them.',
    slug: 'old-house-basements',
    category: 'Renovation',
    readTime: '42 min read',
    image: '/old-house-basement-hero.jpg',
  },
  {
    title: 'Spring Basement Checklist: Preparing for the Wet Season',
    description: 'Complete 13-step spring basement checklist covering gutters, sump pumps, cracks, dehumidifiers, emergency kits, and more.',
    slug: 'spring-basement-checklist',
    category: 'Seasonal',
    readTime: '24 min read',
    image: '/images/spring-basement-checklist/springchecklist.jpg',
  },
  {
    title: 'Best Waterproof Basement Paint & Sealers in 2026',
    description: 'Drylok vs RadonSeal vs KILZ, Liquid Rubber, Thoroseal, Sani-Tred. Compare waterproof basement paints and sealers on cost, performance, and longevity.',
    slug: 'waterproof-basement-paint-sealers',
    category: 'Reviews',
    readTime: '26 min read',
    image: '/images/waterproof-basement-paint-sealers/hero.jpg',
  },
  {
    title: "Basement Flooding Insurance: What's Actually Covered in 2026",
    description: 'Understand what homeowners insurance covers for basement flooding in 2026. NFIP vs private flood insurance, water backup riders, claims tips, and cost data.',
    slug: 'basement-flooding-insurance',
    category: 'Insurance',
    readTime: '28 min read',
    image: '/basement%20flooding%20insurance.jpg',
  },
    {
    title: 'Best Water Leak Detectors & Smart Sensors for Basements 2026',
    description: 'YoLink vs Govee vs Ring vs Flo by Moen. Find the best water leak detector for your basement with our comprehensive review of standalone sensors, smart-home systems, and whole-home shutoff solutions.',
    slug: 'best-water-leak-detectors',
    category: 'Reviews',
    readTime: '14 min read',
    image: '/leaksensor.jpg',
  },
    {
      title: 'Basement Humidity Guide 2026: Ideal Levels, How to Measure & Fix High Humidity',
      description: 'Learn what basement humidity levels are safe in 2026. Ideal range is 30-50% RH. Find out how to measure with a hygrometer and fix high humidity fast.',
      slug: 'basement-humidity-guide',
      category: 'Health & Safety',
      readTime: '12 min read',
            image: '/humidity.jpg',
    },
    {
    title: 'Drylok vs RadonSeal: Which Basement Sealer Is Right for You?',
    description: 'Compare Drylok vs RadonSeal for basement waterproofing. Pros, cons, costs, radon protection, and which sealer wins for your situation.',
    slug: 'drylok-vs-radonseal',
    category: 'Comparison',
    readTime: '18 min read',
    image: '/images/drylok-vs-radonseal/drylockvsradonseal.jpg',
  },
    {
    title: 'French Drain vs Sump Pump: Which Basement Waterproofing System Is Best?',
    description: 'Compare French drain vs sump pump for basement waterproofing. Costs, pros, cons, installation, and why combining both gives the best protection in 2026.',
    slug: 'french-drain-vs-sump-pump',
    category: 'Comparison',
    readTime: '20 min read',
    image: '/images/french-drain-vs-sump-pump/frenchdrain%20vs%20sump%20pump.jpg',
  },
  {
    title: 'Basement Permits Guide: Navigating the Process for Finishing, Renovations, and Conversions',
    description: 'Complete guide to basement finishing permits. When you need a permit, step-by-step process, code requirements, costs, and tips to avoid fines.',
    slug: 'basement-permits-guide',
    category: 'Finishing',
    readTime: '15 min read',
    image: '/images/basement-permits-guide/permits.jpg',
  },
    {
    title: 'Best Vapor Barriers for Basements & Crawl Spaces (2026)',
    description: 'Compare the best vapor barriers for basements and crawl spaces in 2026. Poly sheeting, foil insulation, HDPE membranes, dimpled membranes, and liquid barriers reviewed with pros, cons, and affiliate picks.',
    slug: 'best-vapor-barriers',
    category: 'Reviews',
    readTime: '16 min read',
    image: '/images/best-vapor-barriers/vaporbarrier.jpg',
  },
  {
    title: 'Crawl Space Encapsulation: Complete Guide (2026)',
    description: 'Complete guide to crawl space encapsulation. Learn costs, DIY vs pro installation, materials, step-by-step process, and maintenance tips.',
    slug: 'crawl-space-encapsulation-guide',
    category: 'Waterproofing',
    readTime: '18 min read',
    image: '/images/crawl-space-encapsulation-guide/Crawl Space Encapsulation.jpg',
  },
  {
    title: 'Best Basement Dehumidifiers 2026: Top Picks Reviewed',
    description: 'Find the best basement dehumidifiers for 2026. Expert reviews of top 50-pint models from Midea, hOmeLabs, Frigidaire, GE, and AlorAir for mold prevention and moisture control.',
    slug: 'best-basement-dehumidifiers',
    category: 'Reviews',
    readTime: '14 min read',
    image: '/topdehumidfier.jpg',
  },
  {
    title: 'Submersible vs Pedestal Sump Pump: Which Is Right for Your Basement?',
    description: 'Compare submersible vs pedestal sump pumps. Learn the pros, cons, costs, noise levels, and best uses to pick the right sump pump for your basement in 2026.',
    slug: 'submersible-vs-pedestal-sump-pump',
    category: 'Comparison',
    readTime: '12 min read',
    image: '/submersible vs pedestal sump pump.JPG',
  },
  {
    title: 'Best Sump Pumps for 2026: Top Submersible and Pedestal Picks',
    description: 'See the best sump pumps for 2026, including top-rated submersible and pedestal models with GPH, horsepower, noise levels, and real-world reliability for wet basements.',
    slug: 'best-sump-pumps-2026',
    category: 'Reviews',
    readTime: '10 min read',
    image: '/Submersible.jpg',
  },
    {
    title: 'Best Air Purifiers for Basements 2025',
    description: 'Top-rated air purifiers for basement mold, odors, and poor air quality. Expert picks for every budget with pros, cons, and buying advice.',
    slug: 'best-basement-air-purifiers',
    category: 'Reviews',
    readTime: '12 min read',
        image: '/airpurfierembed.jpg',
  },
  {
        title: 'Drop Ceiling vs. Drywall for Basements: Complete Guide 2026',
              description: 'Compare drop ceilings and drywall for basements. Costs, pros, cons, height requirements, moisture resistance, and which ceiling is right for your 2026 renovation.',
              slug: 'drop-ceiling-vs-drywall',
              category: 'Finishing',
              readTime: '15 min read',
    image: '/images/drop-ceiling-vs-drywall/dropceiling .jpg',
            },
  {
    title: 'Epoxy vs Polyurethane Floor Coating: Which One Should You Choose?',
    description: 'Complete 2026 comparison of epoxy vs polyurethane floor coatings. Pros, cons, costs, durability, UV resistance, and when to use each on your basement or garage floor.',
    slug: 'epoxy-vs-polyurethane-floor-coating',
    category: 'Comparison',
    readTime: '15 min read',
    image: '/images/Epoxy vs Polyurethane hero.jpg',
  },
    {
    title: 'DIY vs Hiring a Pro for Basement Projects: How to Decide',
    description: 'Complete 2026 guide to deciding when to DIY and when to hire a professional for basement projects. Cost comparisons, risk assessments, and decision framework for waterproofing, finishing, and structural work.',
    slug: 'diy-vs-hiring-pro-basement-projects',
    category: 'Comparison',
    readTime: '15 min read',
    image: '/images/DIYvsPro.jpg',
  },
    {
    title: 'Spray Foam vs Rigid Foam Insulation: Which Is Better for Your Basement?',
    description: 'Complete 2026 comparison of spray foam vs rigid foam board insulation for basements. R-values, moisture performance, costs, DIY vs pro installation, and when to use each.',
    slug: 'spray-foam-vs-rigid-foam-insulation',
    category: 'Comparison',
    readTime: '25 min read',
    image: '/images/spraysrigidinsulationhero.jpg',
  },
  {
    title: 'Best Backup Power for Sump Pumps 2026: Generators & Battery Stations',
    description: 'Compare generators, portable power stations, and battery backups for sump pumps. Honest recommendations with pricing from $200 to $10,000.',
    slug: 'backup-power-sump-pumps',
    category: 'Reviews',
    readTime: '18 min read',
    image: '/images/generators.jpg',
  },
]

export function searchArticles(query: string): Article[] {
  if (!query.trim()) return []
  const terms = query.toLowerCase().split(/\s+/)
  return articles.filter((article) => {
    const searchText = `${article.title} ${article.description} ${article.category}`.toLowerCase()
    return terms.every((term) => searchText.includes(term))
  })
}
